### ISSUE TITLE
Scheduling a hangout under the `CB Default` group does not trigger a notification in the #announcements channel on Slack.

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#800]
I've tested this out on staging.codebuddies.org.

To reproduce:
1. Click to create a hangout
2. Select "CodeBuddies Default" as the group
3. Click to schedule the hangout, and notice that the popup does not disappear (it should disappear)
4. Notice the "internal server error", and also the fact that the #codebuddies-ops channel on Slack does not get an automatic notification:

![screen shot 2018-03-16 at 11 26 02 pm](https://user-images.githubusercontent.com/4512699/37552391-7b21dcb6-2971-11e8-897f-70c14c2f1d44.jpg)

Server logs:
```
=> App running at: http://localhost:3000/
I20180316-23:38:15.066(-7)? Exception while invoking method 'createHangout' TypeError: Cannot read property 'hangoutChannels' of undefined
I20180316-23:38:15.068(-7)?     at [object Object].Meteor.methods.createHangout (server/hangouts/methods.js:4:33)
I20180316-23:38:15.068(-7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20180316-23:38:15.069(-7)?     at packages/ddp-server/livedata_server.js:719:19
I20180316-23:38:15.069(-7)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20180316-23:38:15.070(-7)?     at packages/ddp-server/livedata_server.js:717:40
I20180316-23:38:15.071(-7)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20180316-23:38:15.071(-7)?     at packages/ddp-server/livedata_server.js:715:46
I20180316-23:38:15.071(-7)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
I20180316-23:38:15.087(-7)?     at packages/ddp-server/livedata_server.js:559:43```

**Comment by lpatmo** [comment]
Hmm, took a look at this but wasn't able to figure it out. @railsstudent, when you have time, could you take a look? No rush!

**Comment by railsstudent** [comment]
@lpatmo  sure. I will take a look

**Comment by lpatmo** [comment]
Thank you!
